"""mes

Revision ID: 01becc3f344a
Revises: 
Create Date: 2023-04-26 15:44:51.153640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01becc3f344a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customuser',
    sa.Column('id', sa.String(length=223), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'STUDENT', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customuser', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customuser_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customuser_username'), ['username'], unique=True)

    op.create_table('admins',
    sa.Column('id', sa.String(length=223), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['customuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.String(length=223), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['customuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=223), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['customuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('staff')
    op.drop_table('admins')
    with op.batch_alter_table('customuser', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customuser_username'))
        batch_op.drop_index(batch_op.f('ix_customuser_email'))

    op.drop_table('customuser')
    # ### end Alembic commands ###
